// try {
//     f()
// } catch(error) {
//     console.log(thr);
// }